name: sn_2nd
description: A new Flutter project.

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  async: ^2.8.2
  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_database: ^9.0.8
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.3
  font_awesome_flutter: ^9.2.0
  get: ^4.6.1
  http: ^0.13.4
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  shared_preferences: ^2.0.8
  sizer: ^2.0.15
  uuid: ^3.0.6
  velocity_x: ^3.3.0
  file_picker: ^4.5.1
  razorpay_flutter: ^1.3.0
  flutter_login_facebook: ^1.4.1
  country_state_city_picker: ^1.2.8

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  rename: ^2.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.jpeg"

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
    - assets/icons/

